apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: redis
  namespace: redis
spec:
  url: https://helm.redis.io/
  interval: 1h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis-enterprise-operator
  namespace: 
spec:
  releaseName: redis-enterprise-operator
  chart:
    spec:
      chart: redis-enterprise-operator
      version: 8.0.2-6
      sourceRef:
        kind: HelmRepository
        name: redis
        namespace: redis
  interval: 10m
---
apiVersion: app.redislabs.com/v1
kind: RedisEnterpriseCluster
metadata:
  name: rec
  namespace: redis
spec:
  nodes: 3
---
apiVersion: v1
kind: Service
metadata:
  name: rec-ui
  namespace: redis
spec:
  type: NodePort
  ports:
    - port: 8443  
      targetPort: 8443  
      nodePort: 30443
